## QTM 151 Quiz 2 Summary

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

1. A code cell is given that defines a function with one input argument (a number) and one return value (a string). Then a variable is defined, passed to the function, and the output is printed. However, there is a mistake in the code and an error occurs. You have to add a comment to the offending line, briefly explaining what happened. Then run a corrected version of the code in another cell.


In [2]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
array = np.array([list1, list2]) * 2  # Multiplies the entire array, not element-wise sum
print(array)

[[ 2  4  6]
 [ 8 10 12]]


2. A code cell is given that defines two lists of numbers, then attempts to define a Numpy array from the entries of the two lists using a mathematical operation. The code cell runs fine, but the output is different than what was intended. You have to add a comment, briefly explaining why the output of the code is doing something differently. Then run a corrected version of the code in another cell.


In [3]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
array = np.array(list1) + np.array(list2)  # Element-wise addition
print(array)

[5 7 9]


3. Create a DataFrame by reading in a .csv file. The instructions will refer to a specific column/variable of the DataFrame, and a logical condition.  You will be instructed to extract the subset of the data for which this column/variable satisfies the logical condition. The extracted subset should be saved to a separate DataFrame. Then using Python commands, you will need to print out the number of rows in the extracted data set (i.e., how many rows satisfied the logical condition).


In [4]:
df = pd.read_csv('data/heightweight.csv')
df_subset = df.iloc[345:398, :]
subset_sorted = df_subset.sort_values(by='Height_Inches', ascending=True)
print(subset_sorted)

FileNotFoundError: [Errno 2] No such file or directory: 'data/heightweight.csv'

4. Write a function that takes in a single number as an input argument, and returns a single string as the output. The value of the output string is one of two choices, which is determined by whether the input satisfies a logical condition. Then use the .apply() method from Pandas to evaluate this function for every row in a DataFrame. You will be told which column/variable should be input to the function.


In [ ]:
def age_group(age):
    if age < 18:
        return "Minor"
    else:
        return "Adult"

# Apply function
df["age_category"] = df["age"].apply(age_group)

# Show result
print(df[["age", "age_category"]].head())

5. Given a DataFrame, you will want to randomly assign each row to one of two groups. To do so, you will add a new column to the DataFrame called "random_var" which is filled with random numbers from a given distribution. Then you will create two new DataFrames, based on the whether each row's random variable satisfies a given logical condition. These two DataFrames represent the random assignment into two groups.


In [ ]:
df["random_var"] = np.random.rand(len(df))

# Assign groups based on condition
group1 = df[df["random_var"] < 0.5]
group2 = df[df["random_var"] >= 0.5]

print(f"Group 1 size: {len(group1)}")
print(f"Group 2 size: {len(group2)}")

6. Continuing question 5, you will make two scatter plots from the data in each randomly assigned group. So that they appear side-by-side, you will need to use the subplots command from the matplotlib.pyplot library.

In [ ]:
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Scatter plot for Group 1
ax1.scatter(group1["age"], group1["income"], color='blue')
ax1.set_title("Group 1: age vs income")
ax1.set_xlabel("Age")
ax1.set_ylabel("Income")

# Scatter plot for Group 2
ax2.scatter(group2["age"], group2["income"], color='green')
ax2.set_title("Group 2: age vs income")
ax2.set_xlabel("Age")
ax2.set_ylabel("Income")

plt.tight_layout()
plt.show()